using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Security.Cryptography;

// Throwaway spike, not part of the app build. Proves two things needed
// before committing the licensing/upgrade-page implementation plan:
//  1. A minimal, valid PDF can be hand-emitted with only in-box .NET
//     Framework APIs (no library, matches build.cmd's csc.exe-only rule).
//  2. RSA sign/verify works for offline license blobs with no NuGet.
class Spike
{
    static void Main()
    {
        RunPdfSpike();
        RunLicenseSpike();
        Console.WriteLine("SPIKE OK");
    }

    // ---- 1. Minimal hand-rolled PDF writer ----------------------------
    static void RunPdfSpike()
    {
        List<byte[]> objects = new List<byte[]>();

        // Object 1: Catalog
        objects.Add(Ascii("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"));

        // Object 2: Pages
        objects.Add(Ascii("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"));

        // Object 3: Page
        objects.Add(Ascii("3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] " +
            "/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n"));

        // Object 4: Content stream — header text + a filled rect standing in
        // for the Grenat hairline, to prove text + basic graphics both work.
        string content =
            "0.486 0.180 0.227 rg\n" +   // Grenat as fill color (0x7C2E3A normalized)
            "72 740 468 4 re f\n" +      // hairline rule
            "BT /F1 18 Tf 72 700 Td (SINVAUX Aftermath - Incident Report) Tj ET\n" +
            "BT /F1 10 Tf 72 680 Td (Generated by PDF spike - no external library used) Tj ET\n";
        byte[] contentBytes = Ascii(content);
        objects.Add(Ascii("4 0 obj\n<< /Length " + contentBytes.Length + " >>\nstream\n" +
            content + "endstream\nendobj\n"));

        // Object 5: Font
        objects.Add(Ascii("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n"));

        using (MemoryStream ms = new MemoryStream())
        {
            byte[] header = Ascii("%PDF-1.4\n");
            ms.Write(header, 0, header.Length);

            long[] offsets = new long[objects.Count + 1];
            for (int i = 0; i < objects.Count; i++)
            {
                offsets[i + 1] = ms.Position;
                ms.Write(objects[i], 0, objects[i].Length);
            }

            long xrefStart = ms.Position;
            StringBuilder xref = new StringBuilder();
            xref.Append("xref\n0 " + (objects.Count + 1) + "\n");
            xref.Append("0000000000 65535 f \n");
            for (int i = 1; i <= objects.Count; i++)
                xref.Append(offsets[i].ToString("D10") + " 00000 n \n");
            byte[] xrefBytes = Ascii(xref.ToString());
            ms.Write(xrefBytes, 0, xrefBytes.Length);

            string trailer = "trailer\n<< /Size " + (objects.Count + 1) + " /Root 1 0 R >>\n" +
                "startxref\n" + xrefStart + "\n%%EOF";
            byte[] trailerBytes = Ascii(trailer);
            ms.Write(trailerBytes, 0, trailerBytes.Length);

            File.WriteAllBytes(AppDomain.CurrentDomain.BaseDirectory + "spike-output.pdf", ms.ToArray());
        }

        Console.WriteLine("PDF spike wrote spike-output.pdf");
    }

    static byte[] Ascii(string s)
    {
        return Encoding.GetEncoding("ISO-8859-1").GetBytes(s);
    }

    // ---- 2. RSA sign/verify for offline license blobs -----------------
    static void RunLicenseSpike()
    {
        using (RSACryptoServiceProvider rsa = new RSACryptoServiceProvider(2048))
        {
            string payload = "{\"tier\":\"pro\",\"expires\":\"2027-08-10\",\"seat\":\"single\"}";
            byte[] payloadBytes = Encoding.UTF8.GetBytes(payload);

            byte[] signature = rsa.SignData(payloadBytes, new SHA256CryptoServiceProvider());
            string licenseKey = Convert.ToBase64String(payloadBytes) + "." + Convert.ToBase64String(signature);

            // Simulate the app side: only the public key is embedded there.
            RSAParameters publicOnly = rsa.ExportParameters(false);
            using (RSACryptoServiceProvider verifier = new RSACryptoServiceProvider())
            {
                verifier.ImportParameters(publicOnly);
                string[] parts = licenseKey.Split('.');
                byte[] verifyPayload = Convert.FromBase64String(parts[0]);
                byte[] verifySig = Convert.FromBase64String(parts[1]);
                bool ok = verifier.VerifyData(verifyPayload, new SHA256CryptoServiceProvider(), verifySig);
                if (!ok) throw new Exception("License signature FAILED to verify");

                // Tamper check: flipping a byte must fail verification.
                verifyPayload[0] ^= 0xFF;
                bool tamperedOk = verifier.VerifyData(verifyPayload, new SHA256CryptoServiceProvider(), verifySig);
                if (tamperedOk) throw new Exception("Tampered payload incorrectly verified - BAD");
            }
        }

        Console.WriteLine("License spike: RSA-2048 sign/verify OK, tamper correctly rejected");
    }
}
