// Exporter: raw CSV/JSON export (Plus tier). Simpler sibling to PdfWriter -
// no rendering, just the same flat-JSON serialization pattern used
// elsewhere in the app (Baseline.cs, Quarantine.cs), plus a CSV writer.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace Aftermath
{
    public class ExportRow
    {
        public string Item = "";
        public string Location = "";
        public string Verdict = "";
        public string Action = "";
    }

    public static class Exporter
    {
        public static void WriteCsv(List<ExportRow> rows, string outputPath)
        {
            var sb = new StringBuilder();
            sb.Append("# Generated by SINVAUX Aftermath, ");
            sb.Append(DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture));
            sb.Append("\n");
            sb.Append("Item,Location,Verdict,Action\n");
            foreach (var row in rows)
            {
                sb.Append(CsvField(row.Item)); sb.Append(",");
                sb.Append(CsvField(row.Location)); sb.Append(",");
                sb.Append(CsvField(row.Verdict)); sb.Append(",");
                sb.Append(CsvField(row.Action)); sb.Append("\n");
            }
            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
        }

        public static void WriteJson(List<ExportRow> rows, string outputPath)
        {
            var sb = new StringBuilder();
            sb.Append("{\n");
            sb.Append("  \"generatedBy\": \"SINVAUX Aftermath\",\n");
            sb.Append("  \"generatedAtUtc\": \"" + DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture) + "\",\n");
            sb.Append("  \"findings\": [\n");
            for (int i = 0; i < rows.Count; i++)
            {
                var row = rows[i];
                sb.Append("    { \"item\": \"" + Esc(row.Item) + "\", \"location\": \"" + Esc(row.Location) +
                    "\", \"verdict\": \"" + Esc(row.Verdict) + "\", \"action\": \"" + Esc(row.Action) + "\" }");
                sb.Append(i < rows.Count - 1 ? ",\n" : "\n");
            }
            sb.Append("  ]\n}\n");
            File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
        }

        private static string CsvField(string s)
        {
            if (s == null) s = "";
            bool needsQuote = s.Contains(",") || s.Contains("\"") || s.Contains("\n");
            string escaped = s.Replace("\"", "\"\"");
            return needsQuote ? "\"" + escaped + "\"" : escaped;
        }

        private static string Esc(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            var sb = new StringBuilder();
            foreach (char c in s)
            {
                if (c == '\\') sb.Append("\\\\");
                else if (c == '"') sb.Append("\\\"");
                else if (c == '\n') sb.Append("\\n");
                else if (c == '\r') sb.Append("\\r");
                else if (c == '\t') sb.Append("\\t");
                else sb.Append(c);
            }
            return sb.ToString();
        }
    }
}
